apiVersion: v1
kind: Service
metadata:
  name: helloworldapp-service
  labels:
    app: helloworldapp
spec:
  selector:
    app: helloworldapp
  ports:
    - protocol: TCP
      port: 9090  # -----------------------------------------The port your Service exposes
      targetPort: 8080  #----------------------------------- The port your container listens on
  type: ClusterIP