apiVersion: v1  #-------------- Specifies the API version being used for the service resource
kind: Service  #--------------- Defines the resource type as a Kubernetes Service
metadata:
  name: helloworldapp-service  # The name of the service
  labels:
    app: helloworldapp  # -----  Label to identify and group this service with other related resources
spec:
  selector:
    app: helloworldapp  #------- Selects PODS with this label to forward traffic to
  ports:
    - protocol: TCP  
      port: 8080  # ------------ The port on the service that will be exposed within the cluster
      targetPort: 8080  # ------ The port on the container/POD where the application is running
      nodePort: 30080   # ------ The port on the NODE that can be accessed externally (range 30000-32767)
  type: NodePort  #------------- Service type that exposes the application on a specific port of each node